name: hallat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cloud_firestore: 4.17.3
  cloud_firestore_platform_interface: 6.2.3
  cloud_firestore_web: 3.12.3
  collection: 1.18.0
  dropdown_button2: 2.3.9
  firebase_auth: 4.19.5
  firebase_auth_platform_interface: 7.2.6
  firebase_auth_web: 5.11.5
  firebase_core: 2.31.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.17.0
  firebase_dynamic_links: 5.4.16
  firebase_dynamic_links_platform_interface: 0.2.6+24
  firebase_performance: 0.9.4+5
  firebase_performance_platform_interface: 0.1.4+33
  firebase_performance_web: 0.1.6+5
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_google_places: 
    git:
      url: https://github.com/ShehanYjoz/flutter_google_places.git
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_staggered_grid_view: 0.7.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_maps: 7.1.0
  google_maps_flutter: 2.6.1
  google_maps_flutter_android: 2.8.1
  google_maps_flutter_ios: 2.6.1
  google_maps_flutter_platform_interface: 2.7.1
  google_maps_flutter_web: 0.5.7
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.7.6
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  intl: 0.19.0
  json_path: 0.7.2
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: 0.27.7
  share_plus: 9.0.0
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  sticky_headers: 0.3.0+2
  stream_transform: 2.1.0
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.4
  url_launcher_ios: 6.3.1
  url_launcher_platform_interface: 2.3.2

  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  uuid: ^4.0.0
  web: 0.1.4-beta
  collection: 1.17.2  # Override to resolve conflict with flutter_test

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
